spring:
  mvc:
    async:
      request-timeout: 240000
  application:
    name: ka-ching
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/ka_ching
    username: ${MYSQL_USER:user}
    password: ${MYSQL_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active: dev
scheduler:
  currency-fetch-cron: 0 0 12 * * *
app:
  API_KEY: "${MY_API_KEY}"
  API_KEY_FALLBACK: "${MY_API_KEY_FALLBACK}"