spring:
  application:
    name: ka-ching
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://mysql:3306/ka_ching
    username: ${MYSQL_USER:user}
    password: ${MYSQL_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active: dev
scheduler:
  currency-fetch-cron: 0 0 12 * * *
API_KEY: ${API_KEY:}
API_KEY_FALLBACK: ${API_KEY_FALLBACK:}