spring:
  docker:
    compose:
      enabled: false
  mvc:
    async:
      request-timeout: 240000
  application:
    name: ka-ching
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://mysql:3306/ka_ching
    username: ${MYSQL_USER:user}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
scheduler:
  currency-fetch-cron: 0 0 12 * * *

app:
  API_KEY: "${MY_API_KEY}"
  API_KEY_FALLBACK: "${MY_API_KEY_FALLBACK:}"